### ISSUE TITLE
checkbox for hide title is not saving

### ISSUE THREAD

**Issue by andronic90** [ThemeFuse/Unyson-MegaMenu-Extension#8]
After last update cannot hide the mega menu item title, the checkbox is not saving:

![](https://static.md/e890d0d51a12dcd69ce8fd85995df525.png)

**Comment by ghost** [comment]
The problem is in WP, it alters the original/correct `$_POST` value [here](https://github.com/WordPress/WordPress/blob/4.5/wp-admin/nav-menus.php#L52-L75) ([commit](https://github.com/WordPress/WordPress/commit/2bfc0f52188c6f3481635f223e468d9827d01392)).

Proof:
1. Add `fw_print( $_POST['mega-menu'] ); die;` after [this line](https://github.com/ThemeFuse/Unyson-MegaMenu-Extension/blob/v1.0.9/class-fw-extension-megamenu.php#L94)
2. Inspect Element [the checkbox](https://static.md/e890d0d51a12dcd69ce8fd85995df525.png) to find item id in `name="mega-menu[ITEM_ID][title-off]"
3. Check the checkbox and hit Save Menu
4. You should see this wrong value
   
   ![](https://static.md/7581625abe9e5142105fc569807dc110.png)
5. Go Back, Inspect Element the form and find this element
   
   ![](https://static.md/5709b36eab5c626859a40946cb0c7974.png)
6. Delete its `name="nav-menu-data"` attribute
7. Press Save Menu
8. You should see
   
   ![](https://static.md/c05c785660e32d776edcf97bca2f9ed5.png)

**Comment by ghost** [comment]
https://core.trac.wordpress.org/ticket/36590#ticket
